CREATE TABLE [dbo].[Docentes]
(
	[Id] INT NOT NULL IDENTITY, 
    [Nombres] NVARCHAR(30) NULL, 
    [Apellidos] NVARCHAR(30) NULL, 
    [Usuario] NVARCHAR(15) NULL, 
    [Password] NVARCHAR(15) NULL, 
    [Genero] NVARCHAR(10) NULL ,
[Area] NTEXT NULL, 
    [Carrera] TEXT NULL, 
    PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]