//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocentesModulo
    {
        public int Id { get; set; }
        public Nullable<int> Id_Modulo { get; set; }
        public Nullable<int> Id_Docente { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Docente Docente { get; set; }
    }
}
