//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta_estudiante
    {
        public int Id { get; set; }
        public int Id_pregunta { get; set; }
        public int PruebaID { get; set; }
        public int opcion { get; set; }
    
        public virtual Prueba Prueba { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
