//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prueba()
        {
            this.Pregunta_estudiante = new HashSet<Pregunta_estudiante>();
        }
    
        public int PruebaID { get; set; }
        public Nullable<int> ConvocatoriaTestID { get; set; }
        public Nullable<int> Id_estudiante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Calificacion { get; set; }
    
        public virtual ConvocatoriaTest ConvocatoriaTest { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta_estudiante> Pregunta_estudiante { get; set; }
    }
}
